### ISSUE TITLE
ROTEIRO:  QUANTO CUSTA MORAR EM AUSTIN TEXAS? 🏠💲

### ISSUE THREAD

**Issue by kasaustin** [kasaustin/projeto_kasaustin#21]
**Título:** Quanto Custa Morar em Austin, Texas?

### Introdução (0:00 - 0:05)
- **Giullia:** "Quer descobrir o verdadeiro custo de vida em Austin, Texas? E porque achamos a cidade uma excelente opçao para brasileiros"

- **Lucas:** Fique com a gente, pois vamos mergulhar nos detalhes, desde aluguéis até o custo de um café, e dar a você a imagem clara de quanto realmente custa viver aqui em Austin no Texas.

### Abertura (0:06 - 0:20)
- **Giullia:** Olá pessoas! Sou a Giullia

- **Lucas:** E eu sou Lucas, e sejam bem-vindos ao Kasaustin.
---

~ Vinheta do Canal ~

---

### Aluguel e Moradia (0:21 - 1:30)
- **Lucas:** "Primeiro, o aluguel. Austin está crescendo, mas como se compara com outras grandes cidades? Vejam este gráfico [Link para gráfico comparativo de custo de vida](https://www.forbes.com/advisor/mortgages/real-estate/cost-of-living-calculator/orlando-fl/?city=austin-tx&income=150000)"
- **Giullia:** "E para quem pensa em comprar, confiram como os preços de imóveis evoluíram [Link para gráfico de evolução de preços de imóveis em Austin](https://www.redfin.com/city/30818/TX/Austin/housing-market)."

> A gente gastava 3K mais o valor das Utilities, agora reduzimos para 2,3K e sabemos que tem apartamentos de um quarto por 1,8k 1,5k, comentar que existe apartamento para quem ganha menos de X por ano.

### Alimentação e Estilo de Vida (1:31 - 2:30)
- **Giullia:** "Austin é famosa por sua comida incrível. O custo médio de uma refeição aqui é de cerca de $15 a $30. Aqui nao e uma cidade que so tem fast-food, Austin e conhecida pelos seus Foodtrucks, falamos mais sobre isso nesse video (Video de melhores Foodtrucks)"
- **Lucas:** "E não podemos esquecer do estilo de vida ativo. Austin oferece parques e eventos culturais acessíveis. Confira a lista e dicas no nosso instagram `@kasaustin_ofc.`"

> ACL, Trail of Lights, Kite Festival, SXSW many others.
> Falar do cenario musical, Austin e conhecida como a capital da musica ao vivo

### Patrocínio da Nomad (3:30 - 4:00)

- **Integrar Patrocínio:** "Falando em gerenciar finanças, a Nomad, é um cartão com conta digital que funciona onde você pode comprar dólar e usar em mais de 180 países! Com o Nomad, você pode viajar ou morar em Austin sem se preocupar com taxas de câmbio absurdas! CUPOM KASAUSTIN até $20 de cashback.

### Transporte e Mobilidade (2:31 - 3:15)
- **Lucas:** "Sobre a mobilidade, Austin tem algumas opções. Um passe mensal de transporte público custa em torno de $41."
- **Giullia:** "Mas tudo depende de onde voce vai morar, visto que o transporte publico nao chega em algumas partes da cidade, nao vem achando que aqui é igual Sao Paulo, um carro pode ajudar muito"

```
Single. Ride Pass. $1.25. Activated on first ride. No transfers.
Day Pass. $2.50. Valid 24hr, from first ride.
Day Pass. $11.25. Valid 7 days, from first ride.
Day Pass. $41.25. Valid 31 days, from first ride.
```

### Serviços e Utilidades (3:16 - 4:00)
- **Giullia:** "Os custos mensais com serviços básicos como água, luz e internet variam, mas a média fica em torno de $200. Aqui estão algumas dicas para economizar."
- **Lucas:** "Plano de internet sai mais barato se voce fechar pacote de WIFI + Celular. Mercado muito competitivo, as empresas vao te fornecer beneficios para voce migrar para elas, mencionar exemplo da Spectrum com a gente e T-Mobile com o cara da Amazon, forneceram 2 IPhones e pagaram a divida dele com a outra empresa."

### Histórias Pessoais (4:01 - 5:00)
- **Giullia:** "Ouvimos algumas pessoas que se mudaram recentemente para Austin. Vamos compartilhar suas experiências e o que elas acham da cidade [Inserir depoimentos]."

### Encerramento e Chamada para Ação (5:01 - 5:30)
- **Lucas:** "Esperamos que este vídeo tenha te dado uma boa visão sobre viver em Austin. Você acha que vale a pena pelo estilo de vida? Compartilhe sua opinião nos comentários!"
- **Giullia:** "Não se esqueça de curtir, compartilhar e se inscrever para mais conteúdos como este!"

**Comment by lusoal** [comment]
Adicionar valores em todos os topicos pra gente nao precisar ficar procurando na internet na hora que tiver gravando o video, colocar valores em tudo, pegar de outro roteiro que ja fizemos: https://github.com/kasaustin/projeto_kasaustin/issues/11
