### ISSUE TITLE
Roteiro: ''Alerta de Segurança em Austin: O que Todo Brasileiro Precisa Saber! 🚨🇧🇷''

### ISSUE THREAD

**Issue by kasaustin** [kasaustin/projeto_kasaustin#4]
**Roteiro: ''Alerta de Segurança em Austin: O que Todo Brasileiro Precisa Saber! 🚨🇧🇷''**

**Abertura:  Introdução (0:00-0:30)**

**- Local para Gravação: Um parque ou local público em Austin, que seja agradável e tranquilo.**

- **Lucas:** Oi, pessoal! Como vocês estão? Hoje, estamos aqui em
 [nome do local] para falar de algo crucial: segurança em Austin.

- **Giullia:** Vamos abordar golpes comuns, dicas de segurança e como se manter seguro em Austin, especialmente se você é novo na cidade ou está pensando em mudar pra cá.

- L**ucas (CTA Estratégico):** E aí, você já sentiu que não sabia o suficiente sobre a segurança da cidade? Então esse vídeo é pra você! 
 Ah, e não esqueça de dar um 'like' e se inscrever no canal!

- **Vinheta do Canal (0:30-0:35)**

**Primeira Parte: Tipos de Golpes (0:35-4:00)**

**- Local para Gravação: Em frente a um posto policial ou edifício governamental, para contextualizar o tema.**

**- Giullia:** A primeira coisa que você precisa saber são os golpes comuns que acontecem por aqui. Então, presta atenção!

**1)  Vendas Porta a Porta:** Cobram um valor exorbitante por serviços simples. 
Ex: Batem na porta oferecendo serviços como controle de peste, mas com preços exorbitantes.
(b-roll: casas com placas de "Não Perturbe")

**2) Ligações de "Autoridades":** São golpes em que as pessoas se passam por autoridades, como o IRS (a Receita Federal dos EUA), pedindo pagamentos urgentes em cartões-presente.

**3) Aluguel de Imóveis:** Falsas ofertas de aluguel, eles fornecem fotos e informações falsas sobre imóveis para alugar. Depois que a pessoa paga o sinal, o "locador" some.
(b-roll: Passar por outdoors de aluguel de imóveis.Capturar imagens de anúncios de aluguel em postes ou paredes.)

**4) E-mails e Mensagens Falsas:** Como mensagens que parecem ser de bancos pedindo atualização de dados.
(Mostrar como identificar características suspeitas em e-mails.)

**5) Golpes em Redes Sociais:** Ofertas de emprego ou investimentos milagrosos e duvidosos.
(Capturar imagens de anúncios falsos em redes sociais pelo celular. Demonstrar como verificar a autenticidade de uma oferta online.)

**- Gancho para a próxima seção:** Como se proteger desses golpes? Vem comigo que eu te conto!

**- Segunda Parte: Dicas de Segurança (4:00-7:30)**

**- Local para Gravação: Em uma rua movimentada, com várias pessoas e lojas ao redor, para dar a ideia de "vida na cidade".**

- **Lucas:** Tá, a gente já sabe dos golpes, mas como se proteger? Aqui vão algumas dicas!

**1) Pesquise Antes:** Sempre pesquise sobre a empresa ou pessoa com quem está fazendo negócio, também tem muitas coisas que você mesmo consegue fazer sozinho. 
(Mostrar cenas reais lendo avaliações de restaurantes ou serviços locais.)

**2) Desconfie de Ofertas Irresistíveis:** Se parece bom demais pra ser verdade, provavelmente é.

**3) Mantenha Seus Dados Seguros:** Nunca compartilhe informações pessoais por telefone ou e-mail.

**4) Use Aplicativos Confiáveis:** Pra chamar táxis ou carros de app, por exemplo.

**- Gancho para próxima seção:** E aí, já se sente mais seguro? Agora, voce talvez possa estar se perguntando, existem áreas em Austin para se evitar? 

**- Terceira Parte: Áreas a Considerar (7:30-10:00)**

**- Local: Café ao ar livre ou local mais tranquilo.**

**- Giullia:** Muita gente acha que certos bairros são perigosos, mas a verdade é que o crime pode acontecer em qualquer lugar. Nós mesmo, como muitos que acompanham o canal ja sabem, já tivemos problemas de segurança em um bairro considerado bom. Então, sempre fique ligado, não importa onde você esteja.

Fizemos um video no canal mencionando alguns bairro que o crime rate é mais alto, vai estar na descrição caso tenha interesse em assistir.

- **Gancho:** "Então, vamos recapitular?"

**- Conclusão e Recap (10:00-11:30)

- Local: Voltar ao ponto inicial.**

**- Lucas:**
- Recapitulando: Fique atento aos golpes como vendas porta a porta e e-mails falsos.
Tome precauções como pesquisar serviços e manter seus dados seguros.
E lembre-se, crime pode acontecer em qualquer lugar, então sempre fique alerta.

**- CTA Final:** Se você gostou deste vídeo, dê um 'like', compartilhe e se inscreva no canal, considere se tornar membro!

**Comment by lusoal** [comment]
Edicao
